### ISSUE TITLE
Convert DX to Coordinate Plus Scalar Type File

### ISSUE THREAD

**Issue by sbembenek18** [Electrostatics/apbs#283] opened 2023-10-16 20:30 UTC
I'm trying to transform APBS DX grid to a format that is x,y,z along with the electrostatic potential value. This would be useful for other calculations I want to do. 

I'm attaching a bit of working Python code to illustrate. the question is: Am I doing the conversions correctly? 
[apbs_dx_to_coords.py.tar.gz](https://github.com/Electrostatics/apbs/files/12922362/apbs_dx_to_coords.py.tar.gz)

**Comment by sobolevnrm** [comment] 2023-10-23 03:21
This appears to be a duplicate of https://github.com/Electrostatics/apbs/discussions/284.

**Closed by sobolevnrm** 2023-10-23 03:21 UTC
