### ISSUE TITLE
Problem with the installation 

### ISSUE THREAD

**Issue by maribzo** [Electrostatics/apbs#107] opened 2020-11-12 10:16 UTC
Hello, 

I had an issue with the installation of apbs. I got the following error (attached in the file). i did the following commands:
$cmake -DGET_NanoShaper=ON -DENABLE_PYTHON=ON -DBUILD_SHARED_LIBS=OFF ..
$VERBOSE=1 make -j 1 install
Could you help me to solve this problem?
Thank you 
Maria 
[error.txt](https://github.com/Electrostatics/apbs/files/5529809/error.txt)

**Comment by intendo** [comment] 2020-11-12 17:25
The errors seem to come from your system not being able to get Boost from SourceForge.

We have had problems in the past with SourceForge being down for maintenance or the mirrors are unavailable.

You may need to keep trying and look in the error.txt file for the URLs that are trying to download Boost from SourceForce and see if you can download them in your browser.

**Comment by maribzo** [comment] 2020-11-12 17:39
Yes, I can download Boost from SourceForge in my browser. Do you have any suggestions on what should I do next?

**Comment by maribzo** [comment] 2020-11-17 16:41
Hi, I wanted once again to ask about any possibility to fix the problem with the installation. I downloaded the Boost but I don't know how to include this in the installation process.

**Comment by intendo** [comment] 2020-11-30 19:31
@maribzo Another problem may be that you are enabling Python but turning shared libraries off. I think to use Python, you need to also enable shared libraries. I think your options are to enable both or disable both Python and shared libraries.

Another thing I noticed was that the error with boost mentioned that "curl" could not connect to SourceForge.

Can you run the following?
```
curl https://deac-fra.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.gz -o boost_1_60_0.tar.gz
```

If not, then I think the problem may be with your connection to SourceForge through a proxy or firewall issue.
If you can, then I am stumped because I can't recreate the problem.

**Comment by intendo** [comment] 2020-11-30 19:32
@maribzo Another problem may be that you are enabling Python but turning shared libraries off. I think to use Python, you need to also enable shared libraries. I think your options are to enable both or disable both Python and shared libraries.

Another thing I noticed was that the error with boost mentioned that "curl" could not connect to SourceForge.

Can you run the following?
```
curl https://deac-fra.dl.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.gz -o boost_1_60_0.tar.gz
```

If not, then I think the problem may be with your connection to SourceForge through a proxy or firewall issue.
If you can, then I am stumped because I can't recreate the problem.

**Comment by intendo** [comment] 2021-11-10 22:06
@nsoblath has addressed the cause of this issue with the prebuilt version of GeoFlow so we can close this.

**Closed by intendo** 2021-11-10 22:06 UTC
